# Generated by Django 2.2.5 on 2020-04-17 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineMapManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addTime', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('mapNickName', models.CharField(max_length=100, verbose_name='路线简称')),
                ('mapDescription', models.TextField(blank=True, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '路线',
                'verbose_name_plural': '路线管理',
            },
        ),
        migrations.CreateModel(
            name='SingleImageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('creator', models.CharField(blank=True, max_length=20, null=True, verbose_name='creator')),
                ('modifier', models.CharField(blank=True, max_length=20, null=True, verbose_name='modifier')),
                ('creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='creation')),
                ('modification', models.DateTimeField(auto_now=True, null=True, verbose_name='modification')),
                ('title', models.CharField(max_length=120)),
                ('is_identify', models.BooleanField(default=False)),
                ('is_confirm', models.BooleanField()),
                ('is_show', models.BooleanField(default=False)),
                ('is_splice', models.BooleanField(default=False)),
                ('imageOriginPath', models.CharField(max_length=10000, verbose_name='')),
                ('imagePreprocessPath', models.CharField(max_length=10000, verbose_name='')),
                ('imageIdentifyPath', models.CharField(max_length=10000, verbose_name='')),
                ('imageIdentifyResultPath', models.CharField(max_length=10000, verbose_name='')),
                ('imageSplicePath', models.CharField(max_length=10000, verbose_name='')),
                ('overDate', models.CharField(max_length=45, verbose_name='')),
            ],
            options={
                'verbose_name': '图片信息',
                'verbose_name_plural': '图片信息',
            },
        ),
        migrations.CreateModel(
            name='OfflineTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('creator', models.CharField(blank=True, max_length=20, null=True, verbose_name='creator')),
                ('modifier', models.CharField(blank=True, max_length=20, null=True, verbose_name='modifier')),
                ('creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='creation')),
                ('modification', models.DateTimeField(auto_now=True, null=True, verbose_name='modification')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('identify_status', models.CharField(blank=True, choices=[('u', '未识别'), ('d', '已确认'), ('p', '正在确认')], default='u', max_length=6, null=True, verbose_name='识别状态')),
                ('splice_status', models.CharField(blank=True, choices=[('u', '未拼接'), ('d', '已完成'), ('p', '正在拼接')], default='u', max_length=6, null=True, verbose_name='拼接状态')),
                ('preprocess_status', models.CharField(blank=True, choices=[('u', '未处理'), ('d', '已完成'), ('p', '正在预处理')], default='u', max_length=6, null=True, verbose_name='预处理状态')),
                ('comparison_status', models.CharField(blank=True, choices=[('u', '未比对'), ('d', '已完成'), ('p', '正在比对')], default='u', max_length=6, null=True, verbose_name='比对状态')),
                ('imagesOriginPathList', models.CharField(max_length=10000, verbose_name='')),
                ('overDate', models.CharField(max_length=45, verbose_name='')),
                ('title', models.ForeignKey(help_text='请选择路线', on_delete=django.db.models.deletion.CASCADE, to='offlineTask.OfflineMapManage', verbose_name='路线选择')),
            ],
            options={
                'verbose_name': '离线任务',
                'verbose_name_plural': '离线任务',
            },
        ),
    ]
