# Generated by Django 2.2.5 on 2020-04-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offlineTask', '0002_singleimageidentifyinfo_singleimagespliceinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleimageinfo',
            name='imageIdentifyPath',
        ),
        migrations.RemoveField(
            model_name='singleimageinfo',
            name='imageIdentifyResultPath',
        ),
        migrations.RemoveField(
            model_name='singleimageinfo',
            name='imageSplicePath',
        ),
        migrations.RemoveField(
            model_name='singleimageinfo',
            name='is_confirm',
        ),
        migrations.RemoveField(
            model_name='singleimageinfo',
            name='is_identify',
        ),
        migrations.RemoveField(
            model_name='singleimageinfo',
            name='is_splice',
        ),
        migrations.AlterField(
            model_name='singleimageidentifyinfo',
            name='imageIdentifyPath',
            field=models.CharField(max_length=1000, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='singleimageidentifyinfo',
            name='imageIdentifyResultPath',
            field=models.CharField(max_length=1000, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='singleimageidentifyinfo',
            name='imagePreprocessPath',
            field=models.CharField(max_length=1000, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='singleimagespliceinfo',
            name='imagePreprocessPath',
            field=models.CharField(max_length=1000, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='singleimagespliceinfo',
            name='imageSplicePath',
            field=models.CharField(max_length=1000, verbose_name=''),
        ),
    ]
