# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-02-11 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20180921_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='u_predict',
            field=models.IntegerField(default=0),
        ),
    ]
